micronaut:
  application:
    name: keyManager

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    schema-generate: CREATE_DROP

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop

clients:
     erp:
      url: ${URL_ERP_BANCO:`http://localhost:9091/api/v1/clientes/`}